#pragma config(Sensor, in2,    userPot1,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  clawClose,       sensorDigitalOut)
#pragma config(Sensor, dgtl6,  armIn,          sensorDigitalOut)
#pragma config(Sensor, dgtl7,  armOut,         sensorDigitalOut)
#pragma config(Sensor, dgtl8,  ledBeacon,      sensorDigitalOut)
#pragma config(Motor,  port2,           LDrive1,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           LDrive2,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           RDrive1,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           RDrive2,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           Intake,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           BallBatter,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           ledStrips,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

long tmVal = 0;
int flg=0;

task main() {

	SensorValue[clawClose] = 0;
	SensorValue[armIn] = 1;
	SensorValue[armOut] = 0;

	while(true) {
		motor[ledStrips] = SensorValue[userPot1] / -32;

		if( tmVal < time1[ timer1 ] ) {
			tmVal = time1[ timer1 ] + 5000;

			if( flg ) {
				flg = 0;
				SensorValue[ledBeacon] = 0;

				SensorValue[armIn] = 1;
				SensorValue[armOut] = 0;
			}
			else {
				flg = 1;
				SensorValue[ledBeacon] = 1;
				SensorValue[armIn] = 0;
				SensorValue[armOut] = 1;
			}
		}
	}
}
