#pragma config(Sensor, dgtl1,  PSIOUT1,        sensorDigitalOut)
#pragma config(Motor,  port2,           motor1,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           motor2,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           motor3,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           motor4,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           motor5,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           motor6,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool prevButtonState = false;
bool reverse = false;

#define MOTOR_MAX_VALUE			127
#define MOTOR_MIN_VALUE			(-127)

// Macros
#define max( A, B )				A > B ? A : B
#define min( A, B )				A < B ? A : B
#define LimitVal( L, T, H )		max( min( T, H ), L)

task main () {

	wait1Msec( 400 );

	while ( true ) {

    //Flip Functionality

	 	if (vexRT[Btn6D]){
	 		if(prevButtonState == false){
	 			prevButtonState = true;
	 			reverse = !reverse;
	 		}
	 	}
	 	else{
	 		prevButtonState = false;
	 	}
	 	// Scaling factor for flip


	 	 //Motor Drive - Arcade
			int joy_x = -1 * vexRT[Ch1];
			int joy_y = vexRT[Ch3];

			int leftVal = 0;
			int rightVal = 0;

		if(reverse){
				leftVal = LimitVal( MOTOR_MIN_VALUE	, (((joy_x + joy_y)/2)), MOTOR_MAX_VALUE	);
				rightVal = LimitVal( MOTOR_MIN_VALUE	, (((joy_x - joy_y)/2)), MOTOR_MAX_VALUE );
		}
		else{
				leftVal = LimitVal( MOTOR_MIN_VALUE	, (((joy_x - joy_y)/2)), MOTOR_MAX_VALUE );
				rightVal = LimitVal( MOTOR_MIN_VALUE	, (((joy_x + joy_y)/2)), MOTOR_MAX_VALUE );
		}

		   	// Left front
	  		motor[motor1] = leftVal;
	  		// Left back
      	motor[motor2] =  leftVal;

	      // Right front
	      motor[motor3] =  rightVal;
	      // Right back
	      motor[motor4] =  rightVal;


			//Pneumatic System Output Control

		 	if ( vexRT[Btn6UXmtr2] ) {
		 		SensorValue[PSIOUT1]=0;
		 	}
	  	if ( vexRT[Btn6DXmtr2] ) {
		 		SensorValue[PSIOUT1]=1;
		 	}

			//Intake Motor

	 	  if ( vexRT[Btn5UXmtr2] ) {
		 	  motor[motor5] = 96;
		 	}
		  else if ( vexRT[Btn5DXmtr2] ) {
		 		motor[motor5] = -96;
		 	}
		 	else {
		 		motor[motor5] = 0;


		 	if(vexRT[Btn8UXmtr2]){
		 		motor[motor6] = 64;
		 	}
		 	else if(vexRT[Btn8DXmtr2]){
		 		motor[motor6] = -64;
		 	}
		 	else{
		 		motor[motor6] = 0;
		 	}
	  }
	}
}
