#pragma config(Sensor, dgtl2,  ClawClose,      sensorDigitalOut)
#pragma config(Sensor, dgtl3,  CompressEn,     sensorDigitalOut)
#pragma config(Motor,  port2,           mR1,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           mR2,           tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           mL1,           tmotorNone, openLoop)
#pragma config(Motor,  port5,           mL2,           tmotorNone, openLoop)
#pragma config(Motor,  port6,           mIN1,          tmotorNone, openLoop)
#pragma config(Motor,  port7,           mIN2,          tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for three seconds.  There is a    *|
|*  two second pause at the beginning of the program.                                                 *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Power levels that can be assigned to a motor port range from -127 (full reverse) to         *|
|*        127 (full forward).                                                                         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor                   *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	wait1Msec(2);						// Robot waits for 2000 milliseconds before executing program

	// Move forward at full power for 3 seconds
	SensorValue[CompressEn] = 1;	// Enable the compressor.

	motor[mL1] = 127;
	motor[mL2] = 127;
	motor[mR1] = -127;
	motor[mR2] = -127;
	motor[mIN1] = 127;
	motor[mIN2] = -127;


	while( 1 ) {
		SensorValue[ClawClose] = 1;
		wait1Msec( 3000 );
		SensorValue[ClawClose] = 0;
		wait1Msec( 3000 );
	}


	SensorValue[CompressEn] = 0;	// Turn off the compressor.
	SensorValue[ClawClose] = 0;
}												        // Program ends, and the robot stops
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
